# Generated by Django 3.1.1 on 2020-09-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default="settings.MEDIA_URL+str('images/user-secret-solid.svg')", null=True, upload_to='users/%Y/%m/%d/')),
                ('username', models.CharField(max_length=80)),
            ],
        ),
    ]
