# Generated by Django 2.0 on 2020-07-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='author',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
