# Generated by Django 2.0 on 2020-07-12 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0002_auto_20200712_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(related_name='categorie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
