# Generated by Django 2.0 on 2020-06-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200621_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='status',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('pubblicato', 'Pubblicato')], default='draft', max_length=10),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
