# Generated by Django 2.0 on 2020-06-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200622_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='status',
            field=models.CharField(choices=[('bozza', 'Bozza'), ('pubblicato', 'Pubblicato')], default='bozza', max_length=10),
        ),
    ]
