# Generated by Django 2.0 on 2020-06-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200622_1154'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tutorial',
            managers=[
            ],
        ),
    ]
