# Generated by Django 2.0 on 2020-06-22 11:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200622_1218'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tutorial',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
