# Generated by Django 2.0 on 2020-06-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20200622_1308'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tutorial',
            managers=[
            ],
        ),
    ]
