# Generated by Django 3.1.7 on 2021-04-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resp',
            name='postType',
            field=models.CharField(default='resp', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='postType',
            field=models.CharField(default='post', max_length=10),
        ),
    ]
