# Generated by Django 3.0.8 on 2020-11-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201108_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tutorial',
            field=models.CharField(default='free comment', max_length=250),
            preserve_default=False,
        ),
    ]
