# Generated by Django 2.0 on 2021-04-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210403_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default="media/images/user-secret-solid.svg')", null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
